# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac_admin', '0003_auto_20170530_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_name',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='computergroup',
            name='group_id',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='computergroup',
            name='group_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
