# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mac_admin', '0005_auto_20170602_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computergroupmembership',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mac_admin.Computer'),
        ),
    ]
