# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mac_admin', '0006_auto_20170602_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='computergroup',
            name='group_members',
            field=models.ManyToManyField(through='mac_admin.ComputerGroupMembership', to='mac_admin.Computer'),
        ),
        migrations.AddField(
            model_name='computergroupmembership',
            name='assigned_by',
            field=models.CharField(default=b'jss import', max_length=64),
        ),
        migrations.AddField(
            model_name='computergroupmembership',
            name='date_assigned',
            field=models.DateField(default=datetime.datetime(2017, 6, 6, 10, 11, 5, 65494, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='computergroupmembership',
            name='computer_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mac_admin.ComputerGroup'),
        ),
    ]
