# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mac_admin', '0007_auto_20170606_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer_id',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='computergroupmembership',
            name='assigned_by',
            field=models.CharField(default='jss import', max_length=64),
        ),
        migrations.AlterField(
            model_name='computergroupmembership',
            name='date_assigned',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
